### ISSUE TITLE
'Load more Posts 'Not working 

### ISSUE THREAD

**Issue by code-with-sam** [code-with-sam/finallycomments#9]
https://steemit.com/finallycomments/@finallycomments/finally-comments-thread#@bryan-imhoff/finally-uucecgma-

**Comment by Sambillingham** [comment]
@bryan-imhoff mentioned this is still an issue. Should check directly by calling Bryans feed to see if It throws an error I've not noticed before.

**Comment by code-with-sam** [comment]
Tested with username 'bryan-imhoff' not experiencing any issues.
potentially fixed in v0.8.1

**Comment by Sambillingham** [comment]
not reported again since ^
